### ISSUE TITLE
Windows installer flagged as malware

### ISSUE THREAD

**Issue by MichalDobes2** [veusz/veusz.github.io#1]
Hello, the windows installer (veusz-3.2-windows-setup.exe) is flagged as malware by Microsoft Defender, which means that I cannot install it on company PC. Is there any chance something can be done about that?

![image](https://user-images.githubusercontent.com/46783963/76197492-88971400-61ec-11ea-860d-e5a1b16e5569.png)

**Comment by jeremysanders** [comment]
It's a false detection in the Microsoft Defender software. Unfortunately their false detection report page is bugged and I cannot upload any files. I don't know of an email address to complain to. I've complained on social media, with no result yet.

If you want to try reporting this is a false detection, please go to https://www.microsoft.com/en-us/wdsi/filesubmission

Alternatively, if you'd like to donate around 150 euros, I could buy a signing certificate, and I can see if that helps.

**Comment by MichalDobes2** [comment]
Thanks, I will try to report it.

**Comment by jeremysanders** [comment]
I've found a useful page which suggests rebuilding the pyinstaller boot loader. See https://stackoverflow.com/q/43777106/351771 - I've done that and it seems to not be detected by MS Defender any more.

Can you try downloading the latest version of the installer (this is the file 3.2.0.1, linked from the download page)?

**Comment by MichalDobes2** [comment]
Wonderful, thanks!

![image](https://user-images.githubusercontent.com/46783963/76297903-ef81ff00-62b8-11ea-95a6-cb5bb55d9008.png)
